export type Job = {
  id: number
  title: string
  company: string
  logo: string
  location: string
  workMode: "Remote" | "Hybrid" | "On-site"
  salary: string
  exp: string
  posted: string
  type: "Full-time" | "Internship" | "Part-time" | "Contract"
  openings: number
  applicants: number
  desc: string
  responsibilities: string[]
  skills: string[]
  highlights: string[]
  companyInfo: string
  companySize: string
  founded: string
}

export const JOBS: Job[] = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "Apna",
    logo: "A",
    location: "Bangalore",
    workMode: "Hybrid",
    salary: "₹18L – ₹25L / year",
    exp: "3 - 6 years",
    posted: "2 days ago",
    type: "Full-time",
    openings: 3,
    applicants: 142,
    desc: "Build the next generation of India's largest career platform. You will lead frontend architecture using React, TypeScript and a modern design system, partnering closely with design and product to ship delightful, high-performance experiences to millions of users.",
    responsibilities: [
      "Develop and maintain responsive, reusable UI components",
      "Own frontend performance, accessibility and Core Web Vitals",
      "Collaborate with designers to translate Figma into pixel-perfect UI",
      "Mentor junior engineers and drive code-review culture",
    ],
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    highlights: ["Remote-friendly", "ESOPs", "Health insurance", "Flexible hours"],
    companyInfo:
      "Apna is India's largest professional networking and jobs platform, connecting over 50 million members with meaningful career opportunities.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 2,
    title: "Backend Engineer (Node.js)",
    company: "Apna",
    logo: "A",
    location: "Mumbai",
    workMode: "Hybrid",
    salary: "₹16L – ₹22L / year",
    exp: "2 - 5 years",
    posted: "1 week ago",
    type: "Full-time",
    openings: 2,
    applicants: 98,
    desc: "Design and scale microservices, APIs and data pipelines that power career discovery for millions of job seekers. Work with a modern stack and own services end-to-end.",
    responsibilities: [
      "Build and maintain scalable REST and gRPC APIs",
      "Optimise database queries and caching layers",
      "Set up observability, monitoring and alerting",
      "Ensure high availability across services",
    ],
    skills: ["Node.js", "PostgreSQL", "Redis", "Docker", "AWS"],
    highlights: ["Hybrid", "ESOPs", "Latest tech stack", "Learning budget"],
    companyInfo:
      "Apna's backend powers careers for 50M+ members. Join a team that obsesses over reliability and scale.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 3,
    title: "Product Designer",
    company: "Apna",
    logo: "A",
    location: "Delhi",
    workMode: "Remote",
    salary: "₹14L – ₹20L / year",
    exp: "3 - 7 years",
    posted: "3 days ago",
    type: "Full-time",
    openings: 1,
    applicants: 64,
    desc: "Design user-centric experiences for job seekers and recruiters. Drive the end-to-end design process from research to polished, shippable interfaces.",
    responsibilities: [
      "Conduct user research and usability testing",
      "Own and evolve the design system",
      "Create wireframes, prototypes and high-fidelity designs",
      "Partner with engineering on implementation quality",
    ],
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    highlights: ["Remote", "ESOPs", "Creative freedom", "Top gear"],
    companyInfo: "Design drives impact at Apna. Join a small, senior team shaping how India finds work.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    company: "Apna",
    logo: "A",
    location: "Hyderabad",
    workMode: "Hybrid",
    salary: "₹20L – ₹30L / year",
    exp: "4 - 8 years",
    posted: "5 days ago",
    type: "Full-time",
    openings: 2,
    applicants: 51,
    desc: "Manage AWS infrastructure, CI/CD and container orchestration. Ensure high availability and cost efficiency across a fast-growing platform.",
    responsibilities: [
      "Automate deployments and infrastructure with IaC",
      "Build resilient CI/CD pipelines",
      "Drive cost optimisation and capacity planning",
      "Own incident response and disaster recovery",
    ],
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Monitoring"],
    highlights: ["Cloud-first", "ESOPs", "Hybrid", "On-call comp"],
    companyInfo: "Infrastructure that serves millions of requests a day. Scale with us.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "Apna",
    logo: "A",
    location: "Bangalore",
    workMode: "Hybrid",
    salary: "₹22L – ₹35L / year",
    exp: "3 - 6 years",
    posted: "1 day ago",
    type: "Full-time",
    openings: 1,
    applicants: 73,
    desc: "Build recommendation systems and predictive models that match the right candidates to the right jobs at scale.",
    responsibilities: [
      "Design and ship ML models to production",
      "Build feature pipelines and run A/B tests",
      "Partner with product on data-driven decisions",
      "Create dashboards and communicate insights",
    ],
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Spark"],
    highlights: ["Big data", "ESOPs", "AI/ML", "Research time"],
    companyInfo: "Data is at the heart of Apna. Join a team building India's largest career graph.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 6,
    title: "Mobile Engineer (React Native)",
    company: "Apna",
    logo: "A",
    location: "Pune",
    workMode: "Remote",
    salary: "₹15L – ₹22L / year",
    exp: "2 - 4 years",
    posted: "4 days ago",
    type: "Full-time",
    openings: 2,
    applicants: 88,
    desc: "Develop cross-platform mobile apps for iOS and Android used by millions every day.",
    responsibilities: [
      "Build reusable cross-platform components",
      "Integrate native modules and REST APIs",
      "Manage app store releases",
      "Optimise app startup and performance",
    ],
    skills: ["React Native", "TypeScript", "iOS", "Android", "Redux"],
    highlights: ["Remote", "ESOPs", "Mobile-first", "Latest devices"],
    companyInfo: "Apna's mobile app is the front door for millions of job seekers. Build world-class experiences.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 7,
    title: "Marketing Intern",
    company: "Apna",
    logo: "A",
    location: "Mumbai",
    workMode: "Hybrid",
    salary: "₹25k / month",
    exp: "0 - 1 years",
    posted: "2 days ago",
    type: "Internship",
    openings: 4,
    applicants: 210,
    desc: "Assist in marketing campaigns, social media and content creation. A hands-on internship with real ownership.",
    responsibilities: [
      "Support social media planning and execution",
      "Write engaging content and copy",
      "Track campaign performance",
      "Coordinate with design and growth teams",
    ],
    skills: ["Social Media", "Content Writing", "Analytics", "Canva"],
    highlights: ["Hands-on", "Stipend", "Hybrid", "PPO potential"],
    companyInfo: "Kickstart your career with Apna's high-velocity marketing team.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 8,
    title: "HR Business Partner",
    company: "Apna",
    logo: "A",
    location: "Bangalore",
    workMode: "Hybrid",
    salary: "₹12L – ₹18L / year",
    exp: "4 - 8 years",
    posted: "3 days ago",
    type: "Full-time",
    openings: 1,
    applicants: 39,
    desc: "Drive HR strategy, talent acquisition and employee engagement across business units.",
    responsibilities: [
      "Partner with leaders on org design and hiring",
      "Run performance management cycles",
      "Own employee relations and engagement",
      "Champion a people-first culture",
    ],
    skills: ["Talent Management", "Recruitment", "Employee Relations"],
    highlights: ["People-first", "ESOPs", "Hybrid", "Wellness"],
    companyInfo: "Apna's people-first culture is its biggest competitive advantage.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 9,
    title: "Sales Executive",
    company: "Apna",
    logo: "A",
    location: "Delhi",
    workMode: "On-site",
    salary: "₹10L – ₹15L / year",
    exp: "2 - 5 years",
    posted: "1 week ago",
    type: "Full-time",
    openings: 5,
    applicants: 120,
    desc: "Generate leads, pitch to enterprises and close deals with employers hiring at scale.",
    responsibilities: [
      "Own the end-to-end sales cycle",
      "Generate and qualify leads",
      "Conduct client meetings and demos",
      "Maintain a healthy CRM pipeline",
    ],
    skills: ["B2B Sales", "CRM", "Negotiation", "Lead Generation"],
    highlights: ["Incentives", "Growth", "On-site", "Fast promotions"],
    companyInfo: "Join Apna's high-growth enterprise sales engine.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 10,
    title: "Content Writer",
    company: "Apna",
    logo: "A",
    location: "Mumbai",
    workMode: "Remote",
    salary: "₹6L – ₹9L / year",
    exp: "1 - 3 years",
    posted: "2 days ago",
    type: "Full-time",
    openings: 2,
    applicants: 95,
    desc: "Create engaging content for blogs, social media and product. Own the editorial voice of the brand.",
    responsibilities: [
      "Write blogs, newsletters and product copy",
      "Optimise content for SEO",
      "Collaborate with design and marketing",
      "Maintain editorial calendar",
    ],
    skills: ["Writing", "SEO", "Editing", "Content Strategy"],
    highlights: ["Remote", "ESOPs", "Creative", "Flexible"],
    companyInfo: "Words move millions at Apna. Join a team that takes craft seriously.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 11,
    title: "QA Engineer",
    company: "Apna",
    logo: "A",
    location: "Hyderabad",
    workMode: "Hybrid",
    salary: "₹12L – ₹16L / year",
    exp: "3 - 6 years",
    posted: "4 days ago",
    type: "Full-time",
    openings: 2,
    applicants: 47,
    desc: "Ensure quality of web and mobile apps through manual and automated testing.",
    responsibilities: [
      "Design test plans and cases",
      "Build and maintain automation suites",
      "Track and triage bugs",
      "Own release quality gates",
    ],
    skills: ["Selenium", "Cypress", "Test Automation", "API Testing"],
    highlights: ["Quality-first", "ESOPs", "Hybrid", "Learning budget"],
    companyInfo: "Quality is non-negotiable at Apna. Help us ship with confidence.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
  {
    id: 12,
    title: "Product Manager",
    company: "Apna",
    logo: "A",
    location: "Bangalore",
    workMode: "Hybrid",
    salary: "₹25L – ₹35L / year",
    exp: "5 - 10 years",
    posted: "1 day ago",
    type: "Full-time",
    openings: 1,
    applicants: 56,
    desc: "Lead product strategy, roadmap and execution for the core career platform.",
    responsibilities: [
      "Own the product roadmap and vision",
      "Drive data-informed prioritisation",
      "Align stakeholders across functions",
      "Define and track success metrics",
    ],
    skills: ["Product Strategy", "Analytics", "Roadmapping", "A/B Testing"],
    highlights: ["High impact", "ESOPs", "Hybrid", "Ownership"],
    companyInfo: "Product at Apna shapes how India discovers careers.",
    companySize: "1000-5000 employees",
    founded: "2019",
  },
]

export const LOCATIONS = Array.from(new Set(JOBS.map((j) => j.location))).sort()
export const JOB_TYPES = Array.from(new Set(JOBS.map((j) => j.type)))
export const WORK_MODES = Array.from(new Set(JOBS.map((j) => j.workMode)))

export function getJobById(id: number) {
  return JOBS.find((j) => j.id === id)
}

export function getRelatedJobs(id: number, limit = 4) {
  return JOBS.filter((j) => j.id !== id).slice(0, limit)
}
